### ISSUE TITLE
[Bug] 220803 sunah

### ISSUE THREAD

**Issue by ssun-aa** [4rhd6gh/moviemang#129]
~~영화 검색, 클릭 후 페이지 이동 후 스크롤 최상단으로 옮기는 작업 필요~~

~~플레이리스트 생성 화면, _스릴러_ 태그 중복으로 태그 수정 필요~~

~~마이플레이리스트 플레이리스트 페이지네이션 적용 안됨 확인 필요~~

~~영화 검색 후, 플레이리스트 선택 페이지에 전체 플레이리스트 안나옴 페이지네이션 적용 필요~~

~~영화 디테일 화면 좋아요 버튼, 리뷰 탭 삭제 필요~~

~~플레이리스트 디테일에서만 하트 북마크 온클릭 기능 추가 필요~~

~~플레이리스트 카드 화면에서 북마크 아이콘 삭제 필요~~

**Comment by bgradecoding** [comment]
플레이 리스트 생성 화면 스릴러 태그 중복 삭제 (DB 수정)

**Comment by bgradecoding** [comment]
영화 검색, 클릭 후 영화 상세페이지로 이동 후 스크롤 최상단으로 가도록 수정(useEffect에서 scrollTo 사용)

**Comment by bgradecoding** [comment]
마이플레이리스트 플레이리스트 페이지네이션 적용 안됨 확인 필요 ->  수정 완료

**Comment by bgradecoding** [comment]
영화 검색 후, 플레이리스트 선택 페이지에 전체 플레이리스트 안나옴 페이지네이션 적용 필요

-> 추가 완료
