### ISSUE TITLE
[Bug] 검색 페이지 관련

### ISSUE THREAD

**Issue by jihyukma123** [4rhd6gh/moviemang#145]
영화를 검색해서 상세 페이지 조회 후, 다른 영화를 검색해서 상세 페이지 조회 시에 데이터가 로딩되는 동안 직전에 조회했던 영화 페이지가 보여지는 버그가 있습니다.

**Comment by bgradecoding** [comment]
리덕스에 초기화 액션을 추가하고 상세페이지 useEffect에서 호출하여 해결
