### ISSUE TITLE
SNB 하이라이트 관련

### ISSUE THREAD

**Issue by ssun-aa** [4rhd6gh/moviemang#63]
![image](https://user-images.githubusercontent.com/47405655/173190264-0b4920b1-b842-4b76-b973-2ff54a108a84.png)
navlink로 해당 메뉴를 클릭하면 하이라이트를 주려고 하는데 url때문인지 나의 정보는 계속해서 칠해지는 이슈가 발생하네요.

**Comment by ssun-aa** [comment]
![image](https://user-images.githubusercontent.com/47405655/173190620-961d88c8-0801-480e-bd2a-c78318a4489b.png)

![image](https://user-images.githubusercontent.com/47405655/173190612-8de0b796-8f23-4e2d-a069-cf2f651b6a92.png)

**Comment by majih93** [comment]
NavLink에 혹시 `end`라는 prop 전달해도 같은 이슈가 발생할까요?  아래와 같은 형태로 한 번 해봐주시면 감사하겠습니다!
```
<NavLink to='' end>
  {({ isActive }) =>
     isActive ? (
           <text style={{color: blue}}>Home</text>
     ) : (                      
           <text>Home</text>
     )
  }
</NavLink>
```
스택오버플로우에서 이 글 참고하였습니다..ㅋㅋㅋ
> https://stackoverflow.com/questions/70644361/react-router-dom-v6-shows-active-for-index-as-well-as-other-subroutes

**Comment by ssun-aa** [comment]
감사합니다 해결했습니다~
